#!/bin/sh
# https://conventionalcommits.org/
# takes a revset and prepends 'chore: ' to each spelling commit.
if [ "$1" = "message" ]; then
  sed -i -e 's/spelling:/chore: spelling:/' $2
elif [ "$1" = "plan" ]; then
  perl -pi -e 'unless ($second) { s/^pick/edit/; $second=1; } else { s/^pick/mess/ }' $2
else
  EDITOR="$0 plan" hg histedit "$@"
  EDITOR="$0 message" hg histedit --cont
fi
