#!/bin/sh
# ~/bin/convertpatch-to -c.
#
# Output modes:
# perl (MODE=perl):
#   s/teh/the/g
# rs teh the
# g teh; echo the
DIFF="${DIFF:--r master -r spelling}"
case $MODE in
  go)
    # go stands for `grep`(g) + `original`
    # in theory someone might want `grep`(g) + `replacement`
    PREFIX='g "'
    INFIX='"\necho "-> '
    SUFFIX='"\n'
  ;;
  perl)
    PREFIX='s/'
    INFIX='/'
    SUFFIX='/g;\n'
  ;;
  rs|*)
    PREFIX='rs "\\b'
    INFIX='\\b" "'
    SUFFIX='"\n'
  ;;
esac

if [ ! -z "$1" ]; then
    # yes the test is for a single argument and we swallow all of them
    # this lets one do:
    #   convertpatch-to -r spelling%master
    #   convertpatch-to -r master -r spelling
    DIFF="$@"
fi

(d --color always $DIFF -U0|\
    perl -ne '$skip = 1 if /\@\@ -\d+,([^1]|1[^ ])|\@\@ -\d+,\d+ \+\d+,([^1]|1[^ ])/; $skip = 0 if /\@\@ -\d+,1 \+\d+,1 /; next if $skip; print' |\
    perl -ne 'next unless /^\x1b\[0;3[12]m/;s/.*?(\x1b\[0;3[12];1;4m)/$1/g;print'|\
    perl -pne 's/\x1b\[0m.*//' |\
    perl -pne 's!\x1b\[0;31;1;4m(.*)\n!'"$PREFIX"'$1!;s!\x1b\[0;32;1;4m(.*)\n!'"$INFIX"'$1'"$SUFFIX"'!;'
)|sort -u;
