#!/usr/bin/perl -nw
# ~/bin/dn
# parse diff output and return only the content that was not added
#
# This includes context, lines removed, but excludes
# lines that appear to be marking the names of files
next unless /^[- ]/;
next if /^\-{3} /;
s/^.//;
print;
