#!/bin/sh
hgfileexts() {
([ -n "$files" ] && echo "$files" ||
 hg locate 2>/dev/null ||
 git ls-files) |
  perl -ne 's!.*/!!;next unless s!.*\.!!; print'|
  sort -u
}

hgfileignore() {
  hgfileexts | perl -pne 's<^><\\.>;s{\n}{\$\n};'
}

if [ -z "$spelling_base_dir" ]; then
  hgfileexts "$@"
fi
