#!/bin/sh
# ~/bin/hgrmjunk
# Delete files that are generally not useful for spellchecking
SPECS="
'*.cer'
'*.class'
'*.crl'
'*.crt'
'*.csr'
'*.dll'
'*.eot'
'*.exe'
'*.gif'
'*.gz'
'*.icns'
'*.ico'
'*.jar'
'*.jpg'
'*.key'
'*.lock'
'*.lib'
'*.map'
'*.min.*'
'*.otf'
'*.pdf'
'*.pem'
'*.png'
'*.sig'
'*.so'
'*SUMS'
'*.svg'
'*.tar'
'*.tgz'
'*.ttf'
'*.woff*'
'*.xls*'
'*.xpm'
'*.yml'
'*.zip'
.DS_Store
package-lock.json
"
hg locate -0 \
$(for a in $SPECS; do eval echo "$a" | perl -pne 's/([.])/\\$1/g; s/([*])/.*/g; s/(^.*$)/re:(?i)^$1\$/'; done) \
 | xargs -0 hg rm 2>&1|uniq
