#!/usr/bin/perl -w

open AA, ">", "/tmp/local";
open BB, ">", "/tmp/remote";

while (<>) {
  if (m!^---\sa/(.*)!) {
    print AA $1;
  } elsif (m!^\+\+\+\sb/(.*)!) {
    print BB $1;
  } elsif (/^@@/) {
    print AA "\n\n$_";
    print BB "\n\n$_";
  } elsif (/^-(.*)/) {
    for my $token (split /\s+/, $1) {
      print AA "$token\n";
    }
  } elsif (/^\+(.*)/) {
    for my $token (split /\s+/, $1) {
      print BB "$token\n";
    }
  }
}
print AA "\n";
print BB "\n";
close BB;
close AA;

print `wdiff /tmp/local /tmp/remote`;
unlink '/tmp/local';
unlink '/tmp/remote';

