#!/bin/sh
maybe_source=$_
a="/$0"; a=${a%/*}; a=${a#/}; a=${a:-.}; spelling_base_dir=$(cd "$a"; pwd)
sourced=0
if [ -n "$ZSH_EVAL_CONTEXT" ]; then
  case $ZSH_EVAL_CONTEXT in *:file) sourced=1;; esac
elif [ -n "$KSH_VERSION" ]; then
  [ "$(cd $(dirname -- $0) && pwd -P)/$(basename -- $0)" != "$(cd $(dirname -- ${.sh.file}) && pwd -P)/$(basename -- ${.sh.file})" ] &&
    sourced=1 &&
    maybe_source=${.sh.file}
elif [ -n "$BASH_VERSION" ]; then
  (return 0 2>/dev/null) &&
    sourced=1 &&
    maybe_source=$BASH_SOURCE
else # All other shells: examine $0 for known shell binary filenames
  # Detects `sh` and `dash`; add additional shell filenames as needed.
  case ${0##*/} in sh|dash) sourced=1;; esac
fi

if [ "$sourced" = 0 ]; then
  echo "$0 should be sourced" >&2
  exit 1
fi

#a="/$0"; a=${a%/*}; a=${a#/}; a=${a:-.};
spelling_base_dir=$(cd $(dirname $(realpath "$maybe_source")); pwd)
scripts='
g
ge
r
rs
s
hgfileexts
hgfilesample
sort_x
'
for script in $(echo "$scripts"); do
. "$spelling_base_dir/$script"
done
